### ISSUE TITLE
pipx support for migrate script

### ISSUE THREAD

**Issue by flying-sheep** [jupyterlab/hatch-jupyter-builder#62]
### Problem
I have to install this project just to run it once

### Proposed Solution

We could add a `[project.scripts]` table, either with a single entrypoint like

```toml
[project.scripts]
hatch-jupyter-builder = 'hatch_jupyter_builder.cli:run'
```

which can be called as `hatch-jupyter-builder migrate .` and `hatch-jupyter-builder compare-migrated a b [wheel|sdist]`.

Or we could add multiple scripts:

```toml
[project.scripts]
hjb-migrate = 'hatch_jupyter_builder.migrate:run'
hjb-compare-migrated = 'hatch_jupyter_builder.compare_migrated:run'
```
